import { NuqsAdapter } from 'nuqs/adapters/next/app'
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ContextProvider from "./context/contextProvider";
import { Toaster } from "sonner";

// const iranYekan = localFont({
//   src: "https://chakhimarket.netlify.app/fonts/PeydaWebFaNum-bold.woff2",
//   variable: "--font-iranyekan",
//   weight: "100 900",
//   display: 'swap'
// })

// const iranYekaniran = localFont({
//   src: "https://chakhimarket.netlify.app/fonts/IRANYekanXVF.woff",
//   variable: "--font-iranyekaniran",
//   weight: "100 900",
//   display: 'swap'
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
        className={`antialiased`}
      >
        <main>
          <div className="h-screen">
            <NuqsAdapter>
              <ContextProvider>
                {children}
                <Toaster position="bottom-center" />
              </ContextProvider>
            </NuqsAdapter>
          </div>
        </main>
      </body>
    </html>
  );
}
